#!/bin/bash
#Author: Stephanie Alimeta
#date: August 11/2021

echo "This script is for installing JAVA and Jenkins on Centos or  Ubuntu or Amazon"

OS=$(cat /etc/os-release |grep PRETTY_NAME |awk -F'"' '{print $2}'| awk '{print $1}')


if
  [[ $OS == CentOS ]];
then 
  echo "you have $OS operating system"
  sleep 5
  echo "Installing Java and Jenkins"
  sleep 5
sudo yum install wget -y
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum upgrade
sudo yum install jenkins java-11-openjdk-devel -y
sudo systemctl daemon-reload
sudo systemctl start jenkins
sudo systemctl status jenkins

elif
 [[ $OS == Ubuntu ]];
then 
  echo "you have $OS operating system"
  sleep 5
  echo "Installing Java and Jenkins"
sudo apt update -y
sudo apt install openjdk-11-jdk -y
sudo apt-get install wget
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > \
    /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update -y
sudo apt-get install jenkins -y
systemctl start jenkins
systemctl status jenkins

elif [[ $OS == Amazon ]]
then
echo "you have $OS operating system"
sleep 5
echo "installing Java and Jenkins"
sudo yum update –y
yum install wget -y
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum upgrade -y
sudo yum install jenkins java-1.8.0-openjdk-devel -y
sudo systemctl daemon-reload
sudo systemctl start jenkins
sudo systemctl status jenkins

else
echo " your operating system is neither Centos or Ubuntu."
echo " Bye bye"
fi
